version: '3.8'

services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./analysis_results:/app/analysis_results
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped